version: '3'
services:
  api-service:
    container_name: api-service-container
    image: api-service-image
    build:
      context: ./api-service
      dockerfile: Dockerfile
    ports:
      - ${API_SERVICE_PORT}:${API_SERVICE_PORT}
    depends_on:
      - rabbitmq
      - redis
    networks:
      - myapp-network

  user-service:
    container_name: user-service-container
    image: user-service-image
    build:
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - redis
      - mongo
    networks:
      - myapp-network

  logging-service:
    container_name: logging-service-container
    image: logging-service-image
    build:
      context: ./logging-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - myapp-network

  mail-service:
    container_name: mail-service-container
    image: mail-service-image
    build:
      context: ./mail-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - myapp-network

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ Management Plugin
    environment:
      RABBITMQ_DEFAULT_USER: "khalid"
      RABBITMQ_DEFAULT_PASS: "12345"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - myapp-network
    volumes:
      - ./volumes/rabbitmq/:/var/lib/rabbitmq/


  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/broker-redis:/data
    networks:
      - myapp-network


  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./volumes/mongo/:/data/db
    networks:
      - myapp-network

  postgres:
    image: "postgres:15.1-alpine"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - myapp-network

  db-admin:
    container_name: db-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - "${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}"
    networks:
      - myapp-network

#  api-redis:
#    image: "redis:alpine"
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./volumes/broker-redis:/data
#    networks:
#      - myapp-network
#
#  user-redis:
#    image: "redis:alpine"
#    ports:
#      - "6380:6380"
#    volumes:
#      - ./volumes/auth-redis:/data
#    networks:
#      - myapp-network

#  user-db:
#    image: 'mongo:4.2.16-bionic'
#    ports:
#      - ${USER_DB_PORT}:${USER_DB_PORT}
#    environment:
#      MONGO_INITDB_DATABASE: ${USER_DB_DATABASE}
#      MONGO_INITDB_ROOT_USERNAME: ${USER_DB_USER}
#      MONGO_INITDB_ROOT_PASSWORD: ${USER_DB_PASSWORD}
#    volumes:
#      - ./volumes/mongo/:/data/db
#    networks:
#      - myapp-network
#
#  logging-db:
#    image: 'mongo:4.2.16-bionic'
#    ports:
#      - ${LOGGING_DB_PORT}:${LOGGING_DB_PORT}
#    environment:
#      MONGO_INITDB_DATABASE: ${LOGGING_DB_DATABASE}
#      MONGO_INITDB_ROOT_USERNAME: ${LOGGING_DB_USER}
#      MONGO_INITDB_ROOT_PASSWORD: ${LOGGING_DB_PASSWORD}
#    volumes:
#      - ./volumes/mongo/:/data/db
#    networks:
#      - myapp-network

networks:
  myapp-network:
