version: '3'
services:
  broker-service:
    container_name: api-service-container
    image: api-service-image
    build:
      context: ./api-service
      dockerfile: Dockerfile
    ports:
      - ${API_SERVICE_PORT}:80
    depends_on:
      - redis
      - rabbitmq
      #      - db
    networks:
      - myapp-network

  user-service:
    container_name: user-service-container
    image: user-service-image
    build:
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
      - redis
      - rabbitmq
      #      - db
    networks:
      - myapp-network

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ Management Plugin
    environment:
      RABBITMQ_DEFAULT_USER: "khalid"
      RABBITMQ_DEFAULT_PASS: "12345"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - myapp-network
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/

networks:
  myapp-network:
