// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package card_quizzler_service

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Folder struct {
	ID        string
	Title     string
	UserID    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Module struct {
	ID        string
	Title     string
	UserID    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ModuleFolder struct {
	ModuleID string
	FolderID string
}

type Term struct {
	ID          string
	Title       string
	Description string
	ModuleID    string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
